### ISSUE TITLE
Upgrade to 0.19

### ISSUE THREAD

**Issue by ondrejsevcik** [elm-community/elm-undo-redo#11]
Hi, is this package still maintained? I could chip-in and upgrade it to 0.19 eventually.

**Comment by rohanorton** [comment]
Hi! It had slipped my mind to upgrade this. I will do it this weekend, unless you'd like to submit a PR?

**Comment by ondrejsevcik** [comment]
I won't have time this weekend.

**Comment by rohanorton** [comment]
Now available in 0.19

**Comment by ondrejsevcik** [comment]
🙏 great job man!

**Comment by Rolograaf** [comment]
The example script has been updated to 0,19, but the old script is still in the README, and as such in the elm-packages main page for this package...
