### ISSUE TITLE
Drop elm- from package name

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-undo-redo#2]
As per this: https://github.com/elm-community/Manifesto/issues/27.

**Comment by jvoigtlaender** [comment]
@rohanorton, let me know if you need help doing the actual rename of the repository at GitHub.

**Comment by rohanorton** [comment]
Hey, I was going to ask about this. I've looked and I cannot figure out how to do it. I might be wrong, but don't think I have the correct privileges for the repo.

**Comment by jvoigtlaender** [comment]
I've done the GitHub repo rename now.

You'll still have to change the name in the `elm-package.json`, and remove old release tags, before you are able to publish it as a new package to the package site.

**Comment by rohanorton** [comment]
Thanks!
