### ISSUE TITLE
Using with Html.App.program

### ISSUE THREAD

**Issue by cbenz** [elm-community/elm-undo-redo#4]
Hi,

thanks for this nice package!

I'm wondering how to use undo-redo with `Html.App.program` where `update` has this signature: `update : Msg -> Model -> ( Model, Cmd Msg )`. And not `beginnerProgram` with `update : Msg -> Model -> Model` like in the docs.

Should I write an alternative [`update`](https://github.com/elm-community/undo-redo/blob/368582735da7e08134945fad430af4ceabbb4807/src/UndoList.elm#L287-L303) function?

Thanks!

**Comment by mgold** [comment]
Personally I think the entire `update` and `Msg` types are just a bad idea. This is a data structure; it should not dictate the top-level structure of your program, and you've found out exactly why.

Everything you're handling with this package's `Msg` should be done directly by calling the other methods.

**Comment by cbenz** [comment]
Interesting, so I'll try using views returning `Html Msg` (and not `Html (UserList.Msg)` then use directly `UserList.new` in the return values of my `update` function.

**Comment by cbenz** [comment]
The raw commit in my app is https://github.com/cbenz/noteminer/commit/d880c245ec06fb9f10955b1fd8aac42abbffcc23

I can turn this into a mini-doc in the README of this package when I have time :-)

**Comment by rohanorton** [comment]
@mgold I hadn't really considered that the `update` / `Msg` were a bad idea. If this is the case, it would probably be a good idea to stop promoting it in the readme. @cbenz Is this what you're suggesting? Would love to see a PR if you're feeling motivated :)

**Comment by mgold** [comment]
I don't have time to do that myself but I'd love to see PRs!

**Comment by cbenz** [comment]
All right let me a couple of days but I'm doing it. ☺️
