### ISSUE TITLE
undo-redo causing navigation

### ISSUE THREAD

**Issue by sjt003** [elm-community/elm-undo-redo#8]
after a successful ```.undo``` I see the model change reverted but I end up with a different window.location like this ```http://localhost:5000/?title=I+am+changing+a+topic&subtitle=...```. I do not want to issue a route change. I want the route to stay as ```http://localhost:5000/topic/<whatever>```. Unfortunately I can not share specific code samples.

**Comment by rohanorton** [comment]
Hi sjt003,

Could you please provide a bit more detail on how to reproduce this, and if at all possible a minimal, reproducible example?

**Comment by sjt003** [comment]
this was my fault. template error
